name: lab06
on: push
jobs:
  gen_pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install nbconvert ipykernel open-atmos-jupyter-utils
      - run: sudo apt-get update
      - run: sudo apt-get install pandoc inkscape texlive-xetex
      - run: python -m nbconvert --to pdf --execute lab6/MPS_lab6_Konrad_Bodzioch.ipynb
      - uses: actions/upload-artifact@v4
        with:
          path: "lab6/MPS_lab6_Konrad_Bodzioch.pdf"